---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-fdk-rdf-parse-event-publisher.yaml
  - service-fdk-rdf-parse-event-publisher.yaml
images:
  - name: fdk-rdf-parse-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-rdf-parse-event-publisher
    newTag: $(GIT_COMMIT_SHA)
