name: Run tests

on:
  - push

jobs:
  run-tests:
    name: Run tests
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-maven.yaml@main
    with:
      coverage_file_path: ./target/site/jacoco/jacoco.xml
      java_version: 21
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
